server:
  port: 8085

services:
  auth: "http://localhost:8080"
  metadata: "http://localhost:8082"
  streaming: "http://localhost:8090"
  upload: "http://localhost:8081"
  transcoder: "http://localhost:8083"

jwt:
  public_key_path: "keys/public.pem"

rate_limit:
  requests: 5 # Reduced from 10 to 5 to make testing easier
  period: "5s" # Changed from 10s to 5s to make testing faster
