server:
  port: 8085

services:
  auth: "http://localhost:8080"
  metadata: "http://localhost:8082"
  streaming: "http://localhost:8090"
  upload: "http://localhost:8081"
  transcoder: "http://localhost:8083"

jwt:
  public_key_path: "keys/public.pem"

rate_limit:
  requests: 100
  period: "1m"
